import { supabase } from "./supabase-client.js";

const state = { session: null, equipment: [], operators: [] };
let realtimeChannel = null;
const $ = selector => document.querySelector(selector);
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[character]));
const formatDate = value => { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Não informado" : new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(date); };
const timestamp = value => { const result = Date.parse(value ?? ""); return Number.isFinite(result) ? result : null; };
const duration = value => { const minutes = Math.max(1, Math.round((Date.now() - new Date(value)) / 60000)); if (minutes < 60) return `${minutes} min`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours} h`; return `${Math.floor(hours / 24)} d ${hours % 24} h`; };

function showError(error, fallback = "Não foi possível concluir a operação.") {
    const message = error?.message || fallback;
    $("#toast").textContent = message.toLowerCase().includes("row-level security") ? "Acesso bloqueado pelo RLS. Verifique as policies para usuários autenticados." : message;
    $("#toast").classList.add("visible"); window.clearTimeout(showError.timer); showError.timer = window.setTimeout(() => $("#toast").classList.remove("visible"), 7000);
}
function showView(id) { document.querySelectorAll(".view").forEach(view => view.classList.toggle("active", view.id === id)); document.querySelectorAll(".nav-button").forEach(button => button.classList.toggle("active", button.dataset.view === id)); }
async function loadEquipment() { const { data, error } = await supabase.rpc("equipamentos_status_atual"); if (error) throw error; state.equipment = data || []; renderEquipment(); }
function renderEquipment() {
    const query = $("#equipmentSearch").value.toLowerCase(); const filter = $("#statusFilter").value; const sorted = [...state.equipment].sort((a, b) => (a.status === "aberto" ? -1 : 1) - (b.status === "aberto" ? -1 : 1));
    const visible = sorted.filter(item => item.equipamento_id.toLowerCase().includes(query) && (filter === "all" || (filter === "maintenance" ? item.status === "aberto" : item.status === "fechado")));
    $("#totalMetric").textContent = sorted.length; $("#maintenanceMetric").textContent = sorted.filter(item => item.status === "aberto").length; $("#operationalMetric").textContent = sorted.filter(item => item.status === "fechado").length; $("#cyclesMetric").textContent = "—"; $("#resultCount").textContent = `· ${visible.length} exibidos`;
    $("#equipmentList").innerHTML = visible.length ? visible.map(item => { const maintenance = item.status === "aberto"; return `<button class="equipment-row ${maintenance ? "maintenance" : ""}" data-equipment="${escapeHtml(item.equipamento_id)}"><div><div class="equipment-id">${escapeHtml(item.equipamento_id)}</div><div class="subtext">Último ciclo #${escapeHtml(item.id)}</div></div><div><span class="cell-label">Status atual</span><span class="status ${maintenance ? "maintenance" : "operational"}">${maintenance ? "Em manutenção" : "Operacional"}</span></div><div><span class="cell-label">Há quanto tempo</span>${duration(maintenance ? item.data_manutencao : item.data_desbloqueio)}</div><div><span class="cell-label">Responsável</span>${escapeHtml(item.operador_nome || item.operador_id)}</div><span class="arrow">›</span></button>`; }).join("") : `<div class="empty">Nenhum equipamento encontrado para este filtro.</div>`;
    document.querySelectorAll("[data-equipment]").forEach(button => button.addEventListener("click", () => renderDetail(button.dataset.equipment)));
}
async function renderDetail(equipmentId) {
    showView("detailView"); $("#detailContent").innerHTML = `<div class="empty">Carregando histórico...</div>`;
    const { data, error } = await supabase.from("manutencoes").select("*, operadores(nome)").eq("equipamento_id", equipmentId).order("data_manutencao", { ascending: false }); if (error) { showError(error); return; }
    const cycles = data || []; const now = Date.now(); const total = days => cycles.reduce((sum, item) => { const start = timestamp(item.data_manutencao); const end = timestamp(item.data_desbloqueio); const age = start === null ? null : now - start; if (item.status !== "fechado" || start === null || end === null || age < 0 || age >= days * 86400000) return sum; return sum + Math.max(0, end - start); }, 0); const humanHours = milliseconds => `${Math.floor(milliseconds / 3600000)}h ${Math.floor(milliseconds % 3600000 / 60000)}min`;
    $("#detailContent").innerHTML = `<div class="detail-header"><div><p class="eyebrow">Histórico de ciclos</p><h2>${escapeHtml(equipmentId)}</h2></div><div class="detail-stats"><div class="detail-stat"><span class="cell-label">Últimos 7 dias</span><strong>${humanHours(total(7))}</strong></div><div class="detail-stat"><span class="cell-label">Últimos 30 dias</span><strong>${humanHours(total(30))}</strong></div></div></div><div class="history">${cycles.length ? cycles.map(item => `<article class="cycle"><div class="cycle-top"><strong>Ciclo #${escapeHtml(item.id)}</strong><span class="status ${item.status === "aberto" ? "maintenance" : "operational"}">${item.status === "aberto" ? "Em manutenção" : "Fechado"}</span></div><div class="cycle-grid"><div><span class="cell-label">Abertura</span><div>${formatDate(item.data_manutencao)}</div><div class="reason">${escapeHtml(item.motivo_manutencao)}</div></div><div><span class="cell-label">Operador</span><div>${escapeHtml(item.operadores?.nome || item.operador_id)}</div><div class="subtext">${escapeHtml(item.operador_id)}</div></div><div><span class="cell-label">Desbloqueio</span><div>${item.data_desbloqueio ? formatDate(item.data_desbloqueio) : "Ainda em aberto"}</div><div class="reason">${escapeHtml(item.motivo_desbloqueio || "Aguardando liberação")}</div></div></div></article>`).join("") : `<div class="empty">Nenhum ciclo encontrado.</div>`}</div>`;
}
async function loadOperators() { const { data, error } = await supabase.from("operadores").select("*").order("nome"); if (error) throw error; state.operators = data || []; renderOperators(); }
function renderOperators() { const query = $("#operatorSearch").value.toLowerCase(); $("#operatorTableBody").innerHTML = state.operators.filter(operator => operator.nome.toLowerCase().includes(query)).map(operator => `<tr><td><strong>${escapeHtml(operator.operador_id)}</strong></td><td>${escapeHtml(operator.nome)}</td><td>${formatDate(operator.created_at)}</td><td><button class="table-action" data-remove="${escapeHtml(operator.operador_id)}" type="button">Remover</button></td></tr>`).join(""); document.querySelectorAll("[data-remove]").forEach(button => button.addEventListener("click", () => removeOperator(button.dataset.remove))); }
async function addOperator(event) { event.preventDefault(); const { error } = await supabase.from("operadores").insert({ nome: $("#operatorName").value.trim(), operador_id: $("#operatorId").value.trim() }); if (error) { showError(error, "Não foi possível adicionar o operador."); return; } event.target.reset(); await loadOperators(); }
async function removeOperator(operadorId) { const { count, error: checkError } = await supabase.from("manutencoes").select("id", { count: "exact", head: true }).eq("operador_id", operadorId); if (checkError) { showError(checkError); return; } if (count > 0) { showError({ message: "Este operador possui manutenções vinculadas. Desative-o em vez de excluir." }); return; } if (!window.confirm("Remover este operador?")) return; const { error } = await supabase.from("operadores").delete().eq("operador_id", operadorId); if (error) { showError(error, "Não foi possível remover o operador."); return; } await loadOperators(); }
function subscribeToChanges() {
    if (realtimeChannel) return;
    realtimeChannel = supabase.channel("manutencoes-dashboard");
    realtimeChannel.on("postgres_changes", { event: "*", schema: "public", table: "manutencoes" }, async () => { try { await loadEquipment(); $("#lastUpdate").textContent = "Atualizado agora"; } catch (error) { showError(error); } });
    realtimeChannel.subscribe(status => { if (status === "CHANNEL_ERROR") showError({ message: "Não foi possível conectar ao Realtime de manutenções." }); });
}
async function startApp(session) { state.session = session; $("#loginScreen").hidden = true; $("#appShell").hidden = false; $("#sessionUser").textContent = session.user.email; try { await Promise.all([loadEquipment(), loadOperators()]); subscribeToChanges(); } catch (error) { showError(error); } }
async function init() { const { data: { session } } = await supabase.auth.getSession(); if (session) await startApp(session); else $("#loginScreen").hidden = false; supabase.auth.onAuthStateChange(async (event, nextSession) => { if (event === "SIGNED_IN" && nextSession && !state.session) await startApp(nextSession); if (event === "SIGNED_OUT") { state.session = null; if (realtimeChannel) { await supabase.removeChannel(realtimeChannel); realtimeChannel = null; } $("#appShell").hidden = true; $("#loginScreen").hidden = false; } }); }
$("#loginForm").addEventListener("submit", async event => { event.preventDefault(); const { error } = await supabase.auth.signInWithPassword({ email: $("#loginEmail").value, password: $("#loginPassword").value }); if (error) showError(error, "Não foi possível entrar. Confira e-mail e senha."); });
$("#logoutButton").addEventListener("click", async () => { const { error } = await supabase.auth.signOut(); if (error) showError(error); }); $("#operatorForm").addEventListener("submit", addOperator); $("#equipmentSearch").addEventListener("input", renderEquipment); $("#statusFilter").addEventListener("change", renderEquipment); $("#operatorSearch").addEventListener("input", renderOperators); $("#backButton").addEventListener("click", () => showView("equipmentView")); $("#refreshButton").addEventListener("click", async () => { try { await loadEquipment(); $("#lastUpdate").textContent = "Atualizado agora"; } catch (error) { showError(error); } }); document.querySelectorAll(".nav-button").forEach(button => button.addEventListener("click", () => showView(button.dataset.view)));
+init().catch(error => { $("#loginScreen").hidden = false; showError(error, "Não foi possível iniciar o cliente Supabase."); });
